name: Build and test

on:
  push:
    branches:
      - master

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout pg_stats_exporter repository
        uses: actions/checkout@v3
        # In order to fetch changed files
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run cargo-check
        run: cargo check
      - name: Run cargo-fmt
        run: cargo fmt --all -- --check
      - name: Run cargo-clippy
        run: cargo clippy -- -D warnings

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout pg_stats_exporter repository
        uses: actions/checkout@v3
        # In order to fetch changed files
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run tests
        run: |
          cargo test --all -- --nocapture